# Generated by Django 4.2 on 2023-04-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VestidoNoiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoVestido', models.CharField(max_length=200)),
                ('tamanhoDoVestido', models.CharField(max_length=100)),
                ('valorDoVestido', models.FloatField(default=0)),
                ('imagemVestido', models.CharField(max_length=300)),
                ('descricaoVestido', models.TextField(max_length=1000)),
            ],
        ),
    ]
