# Generated by Django 4.2 on 2023-04-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0002_remove_vestidonoiva_imagemvestido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoCliente', models.CharField(max_length=200)),
                ('senhaDoCliente', models.CharField(max_length=200)),
            ],
        ),
    ]
