# Generated by Django 4.2 on 2023-04-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blazer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeBlazer', models.CharField(max_length=200)),
                ('tamanhoBlazer', models.CharField(max_length=100)),
                ('valorBlazer', models.FloatField(default=0)),
                ('descricaoBlazer', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Smoking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSmoking', models.CharField(max_length=200)),
                ('tamanhoSmoking', models.CharField(max_length=100)),
                ('valorSmoking', models.FloatField(default=0)),
                ('descricaoSmoking', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TernoNoivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTernoNoivo', models.CharField(max_length=200)),
                ('tamanhoTernoNoivo', models.CharField(max_length=100)),
                ('valorTernoNoivo', models.FloatField(default=0)),
                ('descricaoTernoNoivo', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VestidoFesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVestidoFesta', models.CharField(max_length=200)),
                ('tamanhoVestidoFesta', models.CharField(max_length=100)),
                ('valorVestidoFesta', models.FloatField(default=0)),
                ('descricaoVestidoFesta', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VestidoFormatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVestidoFormatura', models.CharField(max_length=200)),
                ('tamanhoVestidoFormatura', models.CharField(max_length=100)),
                ('valorVestidoFormatura', models.FloatField(default=0)),
                ('descricaoVestidoFormatura', models.TextField(max_length=1000)),
            ],
        ),
    ]
