# Generated by Django 4.2 on 2023-04-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0004_blazer_smoking_ternonoivo_vestidofesta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vestidoformatura',
            old_name='descricaoVestidoFormatura',
            new_name='descricaoVestido',
        ),
        migrations.RenameField(
            model_name='vestidoformatura',
            old_name='nomeVestidoFormatura',
            new_name='nomeDoVestido',
        ),
        migrations.RenameField(
            model_name='vestidoformatura',
            old_name='tamanhoVestidoFormatura',
            new_name='tamanhoDoVestido',
        ),
        migrations.RenameField(
            model_name='vestidoformatura',
            old_name='valorVestidoFormatura',
            new_name='valorDoVestido',
        ),
    ]
