# Generated by Django 4.2 on 2023-04-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0005_rename_descricaovestidoformatura_vestidoformatura_descricaovestido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestidofesta',
            name='imagemCat',
            field=models.TextField(default='img/festa.jpg'),
        ),
        migrations.AddField(
            model_name='vestidoformatura',
            name='imagemCat',
            field=models.TextField(default='img/formatura.jpg'),
        ),
        migrations.AddField(
            model_name='vestidonoiva',
            name='imagemCat',
            field=models.TextField(default='img/noiva.jpg'),
        ),
    ]
