# Generated by Django 4.2 on 2023-04-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0006_vestidofesta_imagemcat_vestidoformatura_imagemcat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestidonoiva',
            name='imagemCat',
            field=models.TextField(default='noiva.jpg'),
        ),
    ]
