# Generated by Django 4.2 on 2023-04-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0007_alter_vestidonoiva_imagemcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestidonoiva',
            name='imagemCat',
            field=models.TextField(default='img/noiva.jpg'),
        ),
    ]
