# Generated by Django 4.2 on 2023-04-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0008_alter_vestidonoiva_imagemcat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vestidofesta',
            old_name='descricaoVestidoFesta',
            new_name='descricaoVestido',
        ),
        migrations.RenameField(
            model_name='vestidofesta',
            old_name='nomeVestidoFesta',
            new_name='nomeDoVestido',
        ),
        migrations.RenameField(
            model_name='vestidofesta',
            old_name='tamanhoVestidoFesta',
            new_name='tamanhoDoVestido',
        ),
        migrations.RenameField(
            model_name='vestidofesta',
            old_name='valorVestidoFesta',
            new_name='valorDoVestido',
        ),
    ]
