# Generated by Django 4.2 on 2023-04-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0012_remove_roupa_categoria_delete_categoria_delete_roupa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(upload_to='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField(default=0)),
                ('descricao', models.TextField(max_length=1000)),
                ('precoLavagem', models.FloatField(default=30)),
                ('imagem', models.ImageField(upload_to='images')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='cad_roupas.categoria')),
            ],
        ),
    ]
