# Generated by Django 4.2 on 2023-05-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0014_alter_roupa_descricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blazer',
        ),
        migrations.DeleteModel(
            name='Smoking',
        ),
        migrations.DeleteModel(
            name='TernoNoivo',
        ),
        migrations.DeleteModel(
            name='VestidoFesta',
        ),
        migrations.DeleteModel(
            name='VestidoFormatura',
        ),
        migrations.DeleteModel(
            name='VestidoNoiva',
        ),
    ]
