# Generated by Django 4.2 on 2023-05-05 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0017_remove_cliente_nomedocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='preco_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='data_compra',
            field=models.CharField(default='00000', max_length=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 1, 37, 49, 876824)),
        ),
    ]
